# GENERATED BY GEMINI

from app.core.exceptions import (
    AudioServiceError,
    ConfigurationError,
    ExternalServiceError,
    GrandShieldError,
)


def test_grandshield_error_init():
    """Test initialization of the base exception."""
    error = GrandShieldError("Something went wrong")
    assert str(error) == "Something went wrong"
    assert error.original_error is None

def test_grandshield_error_with_original_error():
    """Test initialization with an original error."""
    original = ValueError("Original error")
    error = GrandShieldError("Wrapper error", original_error=original)
    assert str(error) == "Wrapper error"
    assert error.original_error == original

def test_audio_service_error_inheritance():
    """Test that AudioServiceError inherits from GrandShieldError."""
    error = AudioServiceError("Audio failed")
    assert isinstance(error, GrandShieldError)
    assert isinstance(error, Exception)

def test_configuration_error_inheritance():
    """Test that ConfigurationError inherits from GrandShieldError."""
    error = ConfigurationError("Config missing")
    assert isinstance(error, GrandShieldError)

def test_external_service_error_inheritance():
    """Test that ExternalServiceError inherits from GrandShieldError."""
    error = ExternalServiceError("External call failed")
    assert isinstance(error, GrandShieldError)
