
# GENERATED BY GEMINI

import pytest
from pydantic import ValidationError

from app.services.intelligence.models import AnalysisResult, AnalyzedAction, RiskLevel


def test_analysis_result_valid_creation():
    """Test creating a valid AnalysisResult object."""
    result = AnalysisResult(
        risk=RiskLevel.LOW,
        reason="Looks good",
        action=AnalyzedAction.NONE
    )
    assert result.risk == RiskLevel.LOW
    assert result.reason == "Looks good"
    assert result.action == AnalyzedAction.NONE

def test_analysis_result_defaults():
    """Test default values for AnalysisResult."""
    result = AnalysisResult(risk=RiskLevel.HIGH)
    assert result.risk == RiskLevel.HIGH
    assert result.reason == "No significant risk detected."
    assert result.action == AnalyzedAction.NONE

def test_analysis_result_invalid_risk():
    """Test validation error for invalid risk level."""
    with pytest.raises(ValidationError):
        AnalysisResult(risk="MEDIUM")  # "MEDIUM" is not in RiskLevel enum

def test_risk_level_enum_values():
    """Test that RiskLevel enum has expected values."""
    assert RiskLevel.LOW == "LOW"
    assert RiskLevel.HIGH == "HIGH"

def test_analyzed_action_enum_values():
    """Test that AnalyzedAction enum has expected values."""
    assert AnalyzedAction.NONE == "NONE"
    assert AnalyzedAction.ALERT == "ALERT"
