apiVersion: apps/v1
kind: Deployment
metadata:
  name: grandshield
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: grandshield
  template:
    metadata:
      labels:
        app: grandshield
    spec:
      serviceAccountName: default 
      containers:
      - name: backend
        image: 185137893798.dkr.ecr.eu-north-1.amazonaws.com/grandshield/grandshield-ingress:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: ENV
            value: "prod"
          - name: AWS_REGION
            value: "eu-north-1" 
          - name: GOOGLE_API_KEY
            valueFrom:
              secretKeyRef:
                name: grandshield-secrets
                key: google_key
          - name: DEEPGRAM_API_KEY
            valueFrom:
              secretKeyRef:
                name: grandshield-secrets
                key: deepgram_key
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: "0.25"
            memory: "512Mi"
          limits:
            cpu: "0.5"
            memory: "1Gi"