apiVersion: v1
kind: Service
metadata:
  name: grandshield-service
spec:
  selector:
    app: grandshield
  ports:
    - protocol: TCP
      port: 80           
      targetPort: 8000   
  type: LoadBalancer    
